# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    scarica_estrazione:
        class: AppBundle\Service\ScaricaEstrazione
        arguments: [ "%kernel.cache_dir%" ]
    scarica_estrazione_superenalotto:
        class: AppBundle\Service\ScaricaEstrazioneSuperenalotto
        arguments: [ "%kernel.cache_dir%" ]
